# Generated by Django 5.0 on 2025-04-26 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Item')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('image', models.ImageField(upload_to='items/', verbose_name='Imagem')),
                ('lost_location', models.CharField(max_length=100, verbose_name='Local Perdido')),
                ('contact_info', models.CharField(max_length=100, verbose_name='Informações de Contato')),
                ('additional_comments', models.TextField(blank=True, null=True, verbose_name='Comentários Adicionais')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
            ],
            options={
                'verbose_name': 'Item Perdido',
                'verbose_name_plural': 'Itens Perdidos',
                'ordering': ['-created_at'],
            },
        ),
    ]
